33

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -106,7 +106,6 @@ jobs:
               --region $AWS_REGION
             echo "Lambda function created."
           fi
-
   deploy_ec2:
     needs: check_changes
     if: needs.check_changes.outputs.ec2_changed == 'true'
@@ -140,11 +139,16 @@ jobs:
               git clone git@github.com:manikandan0517/ip_feature.git /home/ubuntu/ai-data-integration
             else
               echo "✅ Repository already exists."
+              cd /home/ubuntu/ai-data-integration || exit 1
+              if [ ! -d ".git" ]; then
+                echo "❌ Invalid git repository. Re-cloning the repo..."
+                rm -rf /home/ubuntu/ai-data-integration
+                git clone git@github.com:manikandan0517/ip_feature.git /home/ubuntu/ai-data-integration || { echo "❌ Git clone failed"; exit 1; }
+              else
+                echo "📥 Pulling latest changes from GitHub..."
+                git pull origin main || { echo "❌ Git pull failed"; exit 1; }
+              fi
             fi
-
-            echo "📥 Pulling latest changes from GitHub..."
-            cd /home/ubuntu/ai-data-integration || exit 1
-            git pull origin main || { echo "❌ Git pull failed"; exit 1; }
 
             echo "🐍 Checking/Creating virtual environment..."
             if [ ! -d "venv" ]; then
