35

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -136,15 +136,15 @@ jobs:
             echo "🔄 Checking for existing code..."
             if [ ! -d /home/ubuntu/ai-data-integration ]; then
               echo "🚀 Cloning repository..."
-              git clone git@github.com:manikandan0517/ip_feature.git /home/ubuntu/ai-data-integration
+              git clone git@github.com:manikandan0517/ip_feature.git /home/ubuntu/ai-data-integration1/
             else
               echo "✅ Repository already exists."
-              cd /home/ubuntu/ai-data-integration || exit 1
+              cd /home/ubuntu/ai-data-integration1/ || exit 1
               
               if [ ! -d ".git" ]; then
                 echo "❌ Invalid git repository detected. Re-cloning the repository..."
-                rm -rf /home/ubuntu/ai-data-integration
-                git clone git@github.com:manikandan0517/ip_feature.git /home/ubuntu/ai-data-integration || { echo "❌ Git clone failed"; exit 1; }
+                rm -rf /home/ubuntu/ai-data-integration1/
+                git clone git@github.com:manikandan0517/ip_feature.git /home/ubuntu/ai-data-integration1/ || { echo "❌ Git clone failed"; exit 1; }
               else
                 echo "📥 Pulling latest changes from GitHub..."
                 git reset --hard origin/main  # Resets local changes
